name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:prod --if-present
      - name: Build Project
        uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          SRC_FOLDER: dist
          DEST_OWNER: overrideEg
          DEST_REPO: momeru-adminPanal
          DEST_BRANCH: main
          DEST_FOLDER: dist
          # DEST_PREDEPLOY_CLEANUP: "rm -rf momeru-adminPanal/dist "

      - name: Deploy to Hawzen server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HAWZEN_SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "momeru-adminPanal/dist"
          REMOTE_HOST:  ${{ secrets.HAWZEN_HOST }}
          REMOTE_USER: ${{ secrets.HAWZEN_USERNAME }}
          TARGET: /home/momeru/public_html/panel
          EXCLUDE: "/dist/, /node_modules/"
     
    